<a href="https://colab.research.google.com/github/Sparsh-Srivastava/Paper/blob/main/Subject_Identification_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [172]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [173]:
dataset = pd.read_csv("train.csv")

In [174]:
dataset

ID  ... Quantitative Finance
0          1  ...                    0
1          2  ...                    0
2          3  ...                    0
3          4  ...                    0
4          5  ...                    0
...      ...  ...                  ...
20967  20968  ...                    0
20968  20969  ...                    0
20969  20970  ...                    0
20970  20971  ...                    0
20971  20972  ...                    0

[20972 rows x 9 columns]

In [175]:
dataset = dataset.drop(["ID", "ABSTRACT"], axis=1)

In [176]:
dataset.shape

(20972, 7)

In [177]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, 20972):
  title = re.sub('[^a-zA-z]', ' ', dataset['TITLE'][i])
  title = title.lower()
  title = title.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  all_stopwords.remove("isn't")
  title = [ps.stem(word) for word in title if not word in set(all_stopwords)]
  title = ' '.join(title)
  corpus.append(title)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [178]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2000)
X = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:, 1:].values

In [179]:
X.shape

(20972, 2000)

In [180]:
y.shape

(20972, 6)

In [181]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [182]:
X_train.shape

(16777, 2000)

In [183]:
y_train.shape

(16777, 6)

In [184]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [185]:
X_test.shape

(4195, 2000)

In [186]:
y_pred = classifier.predict(X_test)

In [187]:
y_pred

array([[0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0]])

In [188]:
new_text = ['Transfer_Learning_Application_for_Berries_Yield_Forecasting_using_Deep_Learning']
data = cv.fit_transform(new_text).toarray()
data.resize(2000)
output = classifier.predict([data])
print(output)

[[1 1 0 0 0 0]]


In [189]:
import pickle
with open("model_pickle", "wb") as f:
  pickle.dump(classifier, f)

In [194]:
with open("model_pickle", "rb") as f:
  mp = pickle.load(f)

input = ['Transfer_Learning_Application_for_Berries_Yield_Forecasting_using_Deep_Learning']
data = cv.fit_transform(input).toarray()
data.resize(2000)
output = mp.predict([data])
print(output)

[[1 1 0 0 0 0]]


In [195]:
if output[0][0] == 1:
  print("Computer Science")

if output[0][1] == 1:
  print("Physics")

if output[0][2] == 1:
  print("Mathematics")

if output[0][3] == 1:
  print("Statistics")

if output[0][4] == 1:
  print("Biology")

if output[0][5] == 1:
  print("Finance")

Computer Science
Physics
